//@ pragma ShellId shell

import QtQuick
import QtCore
import Quickshell
import Quickshell.Io
import Quickshell.Hyprland
import "components"

ShellRoot {
  id: root

  // ─── Theme ───────────────────────────────────────────────────────────────
  // Theme.qml is generated by Nix from the colors/font defined in home.nix.
  // Instantiated here so its properties are readable as plain shell properties.
  Theme { id: theme }

  readonly property string bg:           theme.bg
  readonly property string bgElevated:   theme.bgElevated
  readonly property string fg:           theme.fg
  readonly property string fgSubtle:     theme.fgSubtle
  readonly property string accent:       theme.accent
  readonly property string hover:        theme.hover
  readonly property string surface:      theme.surface
  readonly property string selection:    theme.selection
  readonly property string monoFont:     theme.monoFont
  readonly property string flakeDir:     theme.flakeDir
  readonly property string assetDir:     theme.assetDir
  readonly property string wallpaperDir: theme.wallpaperDir
  readonly property string themeDir:     theme.themeDir
  readonly property string stateDir:     theme.stateDir

  // ─── Bar state ───────────────────────────────────────────────────────────
  // Updated every second by bar.sh via statusProcess.
  property string cpuText:       "--"
  property string ramText:       "--"
  property string wifiText:      "󰖪"
  property string bluetoothText: "󰂲"
  property string batteryText:   "󰚥 AC"
  property string volumeText:    "󰕾"
  property string timeText:      Qt.formatDateTime(new Date(), "ddd dd MMM HH:mm:ss")

  // ─── OSD state ───────────────────────────────────────────────────────────
  property bool   osdVisible: false
  property string osdIcon:    ""
  property int    osdValue:   0

  readonly property string homeDir: StandardPaths.writableLocation(StandardPaths.HomeLocation)

  property var launcherScreen: Quickshell.screens.length > 0 ? Quickshell.screens[0] : null
  property string pendingLauncherSubmenu: ""
  property string pendingLauncherMonitor: ""

  // ─── Menu state ──────────────────────────────────────────────────────────
  property bool   menuOpen:           false
  property bool   wallpaperOpen:      false
  property bool   screenshotsOpen:    false
  property bool   screenShareOpen:    false
  property bool   clipboardOpen:      false
  property bool   themeOpen:          false
  property string menuQuery:          ""
  property var    menuStack:          []
  property var    confirmItem:        null
  property string confirmSelection:   "confirm"
  property bool   openedAsSubmenu:    false
  property string performanceProfile: ""
  property bool   menuCalculatorEnabled: true
  property bool   menuWebSearchEnabled:  true

  // Derived item lists — recalculated whenever menuQuery or menuStack changes.
  readonly property var menuItems:           launcher.menuItems
  readonly property var currentMenuItems:    menuStack.length > 0 ? menuStack[menuStack.length - 1].items : menuItems
  readonly property var searchableMenuItems: flattenMenu(currentMenuItems, "")
  readonly property var filteredMenuItems:   getFilteredMenuItems()

  // ─── Menu: navigation ────────────────────────────────────────────────────

  // Push the item's sub-list onto the stack, or run the item's action.
  function enterMenuItem(item) {
    if (item.googleSearch) {
      runDetached("firefox 'https://www.google.com/search?q=" + encodeURIComponent(item.query) + "'")
      closeMenu()
    } else if (item.calculator) {
      runDetached("printf %s '" + item.result + "' | wl-copy")
      closeMenu()
    } else if (item.items) {
      const parentIndex = launcher.menuListItem.currentIndex
      menuStack = menuStack.concat([Object.assign({}, item, { parentIndex: parentIndex })])
      menuQuery = ""
      resetMenuView()
    } else if (item.terminal) {
      const t = item.terminal
      launchTerminal(t.klass, t.title, t.cmd, t.pause || false)
      closeMenu()
    } else if (item.desktop) {
      const entry = DesktopEntries.byId(item.desktop)
      if (entry) entry.execute()
      closeMenu()
    } else if (item.command) {
      if (item.confirm) confirmAction(item)
      else { runDetached(item.command); closeMenu() }
    }
  }

  // Pop the stack, or close if already at the root.
  function menuBack() {
    if (confirmItem) {
      cancelConfirm()
    } else if (openedAsSubmenu) {
      closeMenu()
    } else if (menuStack.length > 0) {
      const previousIndex = menuStack[menuStack.length - 1].parentIndex || 0
      menuStack = menuStack.slice(0, menuStack.length - 1)
      menuQuery = ""
      resetMenuView()
      launcher.menuListItem.currentIndex = previousIndex
    } else {
      closeMenu()
    }
  }

  // Walk the item tree to find a named submenu; fill pathStack with the route.
  function findMenuPath(items, targetName, pathStack) {
    for (let i = 0; i < items.length; i++) {
      const item = items[i]
      if (item.items) {
        const submenu = Object.assign({}, item, { parentIndex: i })
        if (item.name.toLowerCase() === targetName.toLowerCase()) {
          pathStack.push(submenu)
          return true
        }
        pathStack.push(submenu)
        if (findMenuPath(item.items, targetName, pathStack)) return true
        pathStack.pop()
      }
    }
    return false
  }

  function screenForName(name) {
    if (!name) return null
    for (const screen of Quickshell.screens) {
      if (screen.name === name)
        return screen
    }
    return null
  }

  function openLauncherOnActiveWorkspace(submenuName) {
    closeMenu()

    const focusedName = Hyprland.focusedMonitor ? Hyprland.focusedMonitor.name : ""
    const screen = screenForName(focusedName) || launcherScreen || (Quickshell.screens.length > 0 ? Quickshell.screens[0] : null)
    if (screen) launcherScreen = screen
    pendingLauncherMonitor = focusedName

    if (submenuName) {
      let path = []
      if (findMenuPath(menuItems, submenuName, path)) {
        menuStack = path
        openedAsSubmenu = true
      }
    }

    root.menuOpen = true
  }

  onMenuOpenChanged: {
    if (menuOpen) {
      focusMenuInput()
      if (launcher.menuListItem) launcher.menuListItem.currentIndex = 0
      if (root.pendingLauncherMonitor) launcherMoveTimer.restart()
    } else {
      launcherMoveTimer.stop()
      resetMenu()
    }
  }

  // ─── Menu: confirm dialog ────────────────────────────────────────────────

  function confirmAction(item) {
    confirmItem      = item
    confirmSelection = "confirm"
  }

  function cancelConfirm() {
    confirmItem      = null
    confirmSelection = "confirm"
    focusMenuInput()
  }

  function runConfirm() {
    if (confirmItem && confirmItem.command) {
      runDetached(confirmItem.command)
      closeMenu()
    }
  }

  function runConfirmSelection() {
    if (confirmSelection === "confirm") runConfirm()
    else cancelConfirm()
  }

  // ─── Menu: filtering & display ───────────────────────────────────────────

  // Flatten a nested item tree into a searchable list, preserving breadcrumb names.
  function flattenMenu(items, prefix) {
    let flattened = []
    for (const item of items) {
      const displayName = prefix ? prefix + " / " + item.name : item.name
      flattened.push(Object.assign({}, item, { displayName: displayName }))
      if (item.items)
        flattened = flattened.concat(flattenMenu(item.items, displayName))
    }
    return flattened
  }

  function getFilteredMenuItems() {
    const query = menuQuery.trim()
    if (query === "")
      return currentMenuItems

    const matches = searchableMenuItems.filter(item => item.name.toLowerCase().includes(query.toLowerCase()))
    const calculation = menuCalculatorEnabled ? calculate(query) : null

    if (calculation !== null)
      return matches.concat([{ name: query + " = " + calculation, icon: "󰃬", result: calculation, calculator: true }])

    if (matches.length === 0 && menuWebSearchEnabled)
      return [{ name: "Search: " + query, icon: "󰖟", query: query, googleSearch: true }]

    return matches
  }

  // Wrap the query match in an accent-coloured span for the list delegate.
  function highlightedText(text) {
    const value = String(text)
    const query = menuQuery.trim()
    if (query === "") return escapeHtml(value)
    const lowerValue = value.toLowerCase()
    const lowerQuery = query.toLowerCase()
    let result = ""
    let position = 0
    let match = lowerValue.indexOf(lowerQuery, position)
    while (match !== -1) {
      result += escapeHtml(value.slice(position, match))
      result += "<span style=\"color: " + accent + "\">" + escapeHtml(value.slice(match, match + query.length)) + "</span>"
      position = match + query.length
      match = lowerValue.indexOf(lowerQuery, position)
    }
    return result + escapeHtml(value.slice(position))
  }

  // Returns true when item matches the currently active power profile.
  function isCurrentPerformanceItem(item) {
    if (!item || !item.command) return false
    if (item.command === "powerprofilesctl set performance") return performanceProfile === "performance"
    if (item.command === "powerprofilesctl set balanced")    return performanceProfile === "balanced"
    if (item.command === "powerprofilesctl set power-saver") return performanceProfile === "power-saver"
    return false
  }

  // ─── Menu: internal helpers ──────────────────────────────────────────────

  function resetMenuView() {
    if (launcher.menuInputItem) launcher.menuInputItem.text = ""
    if (launcher.menuListItem)  launcher.menuListItem.currentIndex = 0
  }

  function focusMenuInput() {
    if (launcher.menuInputItem) launcher.menuInputItem.forceActiveFocus()
  }

  function resetMenu() {
    menuStack        = []
    confirmItem      = null
    confirmSelection = "confirm"
    menuQuery        = ""
    openedAsSubmenu  = false
    resetMenuView()
  }

  function closeMenu() {
    menuOpen        = false
    wallpaperOpen   = false
    screenshotsOpen = false
    clipboardOpen   = false
    themeOpen       = false
    resetMenu()
  }

  function closeClipboard() {
    clipboardOpen = false
  }

  // ─── Utilities ───────────────────────────────────────────────────────────

  readonly property string terminal: "kitty"

  function launchTerminal(klass, title, cmd, pause) {
    const shellCmd = pause ? cmd + "; echo; read -rp 'Press Enter to close...'" : cmd
    const terminalCmd = "exec " + terminal
      + " --class " + shellQuote(klass)
      + " --title " + shellQuote(title)
      + " -e bash -lic " + shellQuote(shellCmd)
    const finalCmd = "uwsm app -- bash -lc " + shellQuote(terminalCmd)

    launchProcess.command = ["hyprctl", "dispatch", "hl.dsp.exec_cmd(" + luaQuote(finalCmd) + ")"]
    launchProcess.running = true
  }

  // Ask Hyprland to spawn apps so process creation follows the compositor's
  // normal exec path instead of inheriting Quickshell's QProcess scope.
  function runDetached(command) {
    const trimmed = command.trim()
    const shellMeta = /[|&;<>()`$\\\n]/.test(trimmed)
    const finalCmd = trimmed.startsWith("uwsm app")
      ? trimmed
      : shellMeta
        ? "uwsm app -- bash -lc " + shellQuote(trimmed)
        : "uwsm app -- " + trimmed

    launchProcess.command = ["hyprctl", "dispatch", "hl.dsp.exec_cmd(" + luaQuote(finalCmd) + ")"]
    launchProcess.running = true
  }

  function luaQuote(text) {
    return "\"" + String(text)
      .replace(/\\/g, "\\\\")
      .replace(/\"/g, "\\\"")
      .replace(/\n/g, "\\n")
      + "\""
  }

  function shellQuote(text) {
    return "'" + String(text).replace(/'/g, "'\\''") + "'"
  }

  function escapeHtml(text) {
    return String(text)
      .replace(/&/g, "&amp;")
      .replace(/</g, "&lt;")
      .replace(/>/g, "&gt;")
  }

  // Simple recursive-descent calculator for inline expression evaluation.
  function calculate(expression) {
    let text = expression.replace(/\[/g, "(").replace(/\]/g, ")").replace(/×/g, "*").replace(/÷/g, "/")
    text = text.replace(/,/g, ".").replace(/\s+/g, "")
    if (text === "" || !/[0-9]/.test(text) || /[^0-9+\-*/^().]/.test(text))
      return null

    let index = 0
    function peek()    { return text[index] }
    function consume(t){ if (text[index] === t) { index++; return true } return false }

    function parseNumber() {
      const start = index
      while (/[0-9.]/.test(peek() || "")) index++
      if (start === index) throw "number expected"
      const raw = text.slice(start, index)
      if ((raw.match(/\./g) || []).length > 1) throw "invalid number"
      return Number(raw)
    }
    function parsePrimary() {
      if (consume("+")) return parsePrimary()
      if (consume("-")) return -parsePrimary()
      if (consume("(")) { const v = parseAddSub(); if (!consume(")")) throw "missing )"; return v }
      return parseNumber()
    }
    function parsePower()  { let v = parsePrimary(); if (consume("^")) v = Math.pow(v, parsePower()); return v }
    function parseMulDiv() {
      let v = parsePower()
      while (true) {
        if      (consume("*")) v *= parsePower()
        else if (consume("/")) v /= parsePower()
        else return v
      }
    }
    function parseAddSub() {
      let v = parseMulDiv()
      while (true) {
        if      (consume("+")) v += parseMulDiv()
        else if (consume("-")) v -= parseMulDiv()
        else return v
      }
    }

    try {
      const value = parseAddSub()
      if (index !== text.length || !isFinite(value)) return null
      return Number(value.toFixed(10)).toString()
    } catch (e) { return null }
  }

  // ─── Launcher monitor correction ─────────────────────────────────────────
  // Hyprland places new floating windows on whichever monitor it picks at map
  // time, ignoring Quickshell's screen hint. We correct this two ways:
  //
  // Fast path — activewindow event: fires when the launcher gains Hyprland
  // focus. The launcher is then the active window so window.move works.
  //
  // Fallback timer (300 ms): in case Hyprland doesn't grant focus quickly
  // enough, we explicitly re-focus by title then move and centre.

  Connections {
    target: Hyprland
    function onRawEvent(event) {
      if (!root.pendingLauncherMonitor) return
      if (event.name !== "activewindow") return
      // data format: "org.quickshell>>shell-launcher"
      if (!event.data.endsWith(">>shell-launcher")) return
      launcherMoveTimer.stop()
      Hyprland.dispatch("hl.dsp.window.move({monitor=\"" + root.pendingLauncherMonitor + "\"})")
      Hyprland.dispatch("hl.dsp.window.center()")
      root.pendingLauncherMonitor = ""
    }
  }

  Timer {
    id: launcherMoveTimer
    interval: 300
    onTriggered: {
      if (!root.pendingLauncherMonitor || !root.menuOpen) return
      // Only act if the launcher is actually the active window — never touch other windows.
      const active = Hyprland.activeToplevel
      if (!active || active.title !== "shell-launcher") return
      Hyprland.dispatch("hl.dsp.window.move({monitor=\"" + root.pendingLauncherMonitor + "\"})")
      Hyprland.dispatch("hl.dsp.window.center()")
      root.pendingLauncherMonitor = ""
    }
  }

  // ─── Processes ───────────────────────────────────────────────────────────

  Process { id: launchProcess }

  // Parses the pipe-delimited output of bar.sh into individual status fields.
  Process {
    id: statusProcess
    stdout: StdioCollector {
      onStreamFinished: {
        const parts = this.text.trim().split("|")
        if (parts.length >= 5) {
          root.cpuText       = parts[0]
          root.ramText       = parts[1]
          root.wifiText      = parts[2]
          root.bluetoothText = parts[3]
          root.batteryText   = parts[4]
          if (parts.length >= 6) root.volumeText = parts[5]
        }
      }
    }
  }

  Process {
    id: profileProcess
    stdout: StdioCollector {
      onStreamFinished: root.performanceProfile = this.text.trim()
    }
  }

  // ─── Timer ───────────────────────────────────────────────────────────────

  Timer {
    id: osdTimer
    interval: 2000
    onTriggered: root.osdVisible = false
  }

  Timer {
    interval: 1000
    running: true
    repeat: true
    triggeredOnStart: true
    onTriggered: {
      root.timeText = Qt.formatDateTime(new Date(), "ddd dd MMM HH:mm:ss")

      statusProcess.running = false
      statusProcess.command = ["bash", "-c", root.assetDir + "/shell/scripts/bar.sh"]
      statusProcess.running = true

      profileProcess.running = false
      profileProcess.command = ["bash", "-c", "command -v powerprofilesctl >/dev/null 2>&1 && powerprofilesctl get || true"]
      profileProcess.running = true
    }
  }

  // ─── IPC ─────────────────────────────────────────────────────────────────

  IpcHandler {
    target: "theme"
    function open(): void   { root.closeMenu(); root.themeOpen = true }
    function toggle(): void { root.closeMenu(); root.themeOpen = !root.themeOpen }
  }

  IpcHandler {
    target: "wallpaper"
    function open(): void   { root.closeMenu(); root.wallpaperOpen = true }
    function toggle(): void { root.closeMenu(); root.wallpaperOpen = !root.wallpaperOpen }
  }

  IpcHandler {
    target: "screenshare"
    function open(resultPath: string, sourcePath: string): void {
      root.closeMenu()
      screenShare.openPicker(resultPath, sourcePath)
    }
    function close(): void { root.screenShareOpen = false }
  }

  IpcHandler {
    target: "screenshots"
    function open(): void   { root.closeMenu(); root.screenshotsOpen = true }
    function toggle(): void {
      if (root.screenshotsOpen) root.screenshotsOpen = false
      else { root.closeMenu(); root.screenshotsOpen = true }
    }
  }

  IpcHandler {
    target: "clipboard"
    function open(): void   { root.closeMenu(); root.clipboardOpen = true }
    function toggle(): void {
      if (root.clipboardOpen) root.clipboardOpen = false
      else { root.closeMenu(); root.clipboardOpen = true }
    }
  }

  IpcHandler {
    target: "osd"
    // Expects a single "icon:value" string, e.g. "󰕾:75"
    function trigger(data: string): void {
      const sep = data.lastIndexOf(":")
      root.osdIcon    = data.slice(0, sep)
      root.osdValue   = parseInt(data.slice(sep + 1)) || 0
      root.osdVisible = true
      osdTimer.restart()
    }
  }

  IpcHandler {
    target: "launcher"
    function open(): void { root.openLauncherOnActiveWorkspace("") }
    function toggle(): void {
      if (root.menuOpen) root.closeMenu()
      else root.openLauncherOnActiveWorkspace("")
    }
    function openSubmenu(targetName: string): void { root.openLauncherOnActiveWorkspace(targetName) }
  }

  // ─── Windows ─────────────────────────────────────────────────────────────

  // One Bar per monitor, each bound to its own screen.
  Variants {
    model: Quickshell.screens
    Bar {
      required property var modelData
      screen: modelData
      shell: root
    }
  }

  Variants {
    model: Quickshell.screens
    Osd {
      required property var modelData
      screen: modelData
      shell: root
    }
  }

  ThemePicker { shell: root }
  Menu        { id: launcher;        shell: root }
  Clipboard   { id: clipboardWindow; shell: root }
  Screenshare { id: screenShare;     shell: root }
  Screenshots { shell: root }
  Wallpaper   { shell: root }
}
