{ config, configDir, ... }:

{
  wayland.windowManager.hyprland = {
    enable = true;
    systemd.enable = false; # UWSM handles the session
  };

  xdg.configFile."hypr/hyprland.lua".text = ''
    local config_dir = "${configDir}/config/hyprland"

    -- Generated by home-manager so configDir only needs changing in home.nix.
    dofile(config_dir .. "/_startup.lua")
    dofile(config_dir .. "/monitors.lua")
    dofile(config_dir .. "/settings.lua")
    dofile(config_dir .. "/animations.lua")
    dofile(config_dir .. "/keybindings.lua")
    dofile(config_dir .. "/windowrules.lua")
  '';
}
