//@ pragma ShellId shell

import QtQuick
import QtCore
import Quickshell
import Quickshell.Io
import Quickshell.Hyprland
import "components"

ShellRoot {
    id: root

    // ─── Theme ───────────────────────────────────────────────────────────────
    // Theme.qml is generated by Nix from the colors/font defined in home.nix.
    // Instantiated here so its properties are readable as plain shell properties.
    Theme {
        id: theme
    }

    // ── Surfaces ─────────────────────────────────────────────────────────────
    readonly property string crust: theme.crust
    readonly property string mantle: theme.mantle
    readonly property string base: theme.base
    readonly property string surface: theme.surface
    readonly property string overlay: theme.overlay
    readonly property string border: theme.border

    // ── Text ─────────────────────────────────────────────────────────────────
    readonly property string text: theme.text
    readonly property string subtext: theme.subtext
    readonly property string muted: theme.muted
    readonly property string faint: theme.faint

    // ── Accent ───────────────────────────────────────────────────────────────
    readonly property string accent: theme.accent

    // ── Hues ─────────────────────────────────────────────────────────────────
    readonly property string red: theme.red
    readonly property string orange: theme.orange
    readonly property string yellow: theme.yellow
    readonly property string green: theme.green
    readonly property string teal: theme.teal
    readonly property string cyan: theme.cyan
    readonly property string blue: theme.blue
    readonly property string purple: theme.purple

    // ── Terminal ANSI (normal) ────────────────────────────────────────────────
    readonly property string black: theme.black
    readonly property string white: theme.white

    // ── Terminal ANSI (bright) ────────────────────────────────────────────────
    readonly property string brightBlack: theme.brightBlack
    readonly property string brightRed: theme.brightRed
    readonly property string brightGreen: theme.brightGreen
    readonly property string brightYellow: theme.brightYellow
    readonly property string brightBlue: theme.brightBlue
    readonly property string brightPurple: theme.brightPurple
    readonly property string brightCyan: theme.brightCyan
    readonly property string brightWhite: theme.brightWhite

    readonly property string monoFont: theme.monoFont
    readonly property string flakeDir: theme.flakeDir
    readonly property string assetDir: theme.assetDir
    readonly property string wallpaperDir: theme.wallpaperDir
    readonly property string themeDir: theme.themeDir
    readonly property string stateDir: theme.stateDir

    // ─── Bar state ───────────────────────────────────────────────────────────
    property bool barVisible: true

    // Updated every second by bar.sh via statusProcess.
    property string ramText: "--"
    property string wifiText: "󰖪"
    property string bluetoothText: "󰂲"
    property string batteryText: "󰚥 AC"
    property string volumeText: "󰕾"
    property string screenShareText: ""
    property string timeText: Qt.formatDateTime(new Date(), "ddd dd MMM HH:mm:ss")

    // ─── OSD state ───────────────────────────────────────────────────────────
    property bool osdVisible: false
    property string osdIcon: ""
    property int osdValue: 0

    readonly property string homeDir: StandardPaths.writableLocation(StandardPaths.HomeLocation)

    property var launcherScreen: Quickshell.screens.length > 0 ? Quickshell.screens[0] : null
    property var processScreen: Quickshell.screens.length > 0 ? Quickshell.screens[0] : null
    property string pendingLauncherSubmenu: ""
    property string activeLauncherSubmenu: ""

    // ─── MenuSearch state ──────────────────────────────────────────────────────────
    property bool menuOpen: false
    property bool processOpen: false
    property bool wallpaperOpen: false
    property bool themeOpen: false
    property string menuQuery: ""
    property var menuStack: []
    property var confirmItem: null
    property string confirmSelection: "confirm"
    property bool openedAsSubmenu: false
    property string performanceProfile: ""
    property bool menuCalculatorEnabled: true
    property bool menuWebSearchEnabled: true

    // Derived item lists — recalculated whenever menuQuery or menuStack changes.
    readonly property var menuItems: launcher.menuItems
    readonly property var currentMenuItems: menuStack.length > 0 ? menuStack[menuStack.length - 1].items : menuItems
    readonly property var searchableMenuItems: flattenMenu(currentMenuItems, "")
    readonly property var filteredMenuItems: getFilteredMenuItems()

    // ─── MenuSearch: navigation ────────────────────────────────────────────────────

    // Push the item's sub-list onto the stack, or run the item's action.
    function enterMenuItem(item) {
        if (item.googleSearch) {
            runDetached("firefox 'https://www.google.com/search?q=" + encodeURIComponent(item.query) + "'");
            root.menuOpen = false;
        } else if (item.calculator) {
            runDetached("printf %s '" + item.result + "' | wl-copy");
            root.menuOpen = false;
        } else if (item.items) {
            const parentIndex = launcher.menuListItem.currentIndex;
            menuStack = menuStack.concat([Object.assign({}, item, {
                    parentIndex: parentIndex
                })]);
            menuQuery = "";
            resetMenuView();
        } else if (item.terminal) {
            const t = item.terminal;
            launchTerminal(t.klass, t.title, t.cmd, t.pause || false);
            root.menuOpen = false;
        } else if (item.desktop) {
            launchDesktop(item.desktop);
            root.menuOpen = false;
        } else if (item.command) {
            if (item.confirm)
                confirmAction(item);
            else {
                runDetached(item.command);
                root.menuOpen = false;
            }
        }
    }

    // Pop the stack, or close if already at the root.
    function menuBack() {
        if (confirmItem) {
            cancelConfirm();
        } else if (openedAsSubmenu) {
            root.menuOpen = false;
        } else if (menuStack.length > 0) {
            const previousIndex = menuStack[menuStack.length - 1].parentIndex || 0;
            menuStack = menuStack.slice(0, menuStack.length - 1);
            menuQuery = "";
            resetMenuView();
            launcher.menuListItem.currentIndex = previousIndex;
        } else {
            root.menuOpen = false;
        }
    }

    // Walk the item tree to find a named submenu; fill pathStack with the route.
    function findMenuPath(items, targetName, pathStack) {
        for (let i = 0; i < items.length; i++) {
            const item = items[i];
            if (item.items) {
                const submenu = Object.assign({}, item, {
                    parentIndex: i
                });
                if (item.name.toLowerCase() === targetName.toLowerCase()) {
                    pathStack.push(submenu);
                    return true;
                }
                pathStack.push(submenu);
                if (findMenuPath(item.items, targetName, pathStack))
                    return true;
                pathStack.pop();
            }
        }
        return false;
    }

    function screenForName(name) {
        if (!name)
            return null;
        for (const screen of Quickshell.screens) {
            if (screen.name === name)
                return screen;
        }
        return null;
    }

    onMenuOpenChanged: {
        if (menuOpen) {
            focusMenuInput();
            if (launcher.menuListItem)
                launcher.menuListItem.currentIndex = 0;
        } else {
            resetMenu();
        }
    }

    // ─── MenuSearch: confirm dialog ────────────────────────────────────────────────

    function confirmAction(item) {
        confirmItem = item;
        confirmSelection = "confirm";
    }

    function cancelConfirm() {
        confirmItem = null;
        confirmSelection = "confirm";
        focusMenuInput();
    }

    function runConfirm() {
        if (confirmItem && confirmItem.command) {
            runDetached(confirmItem.command);
            root.menuOpen = false;
        }
    }

    function runConfirmSelection() {
        if (confirmSelection === "confirm")
            runConfirm();
        else
            cancelConfirm();
    }

    // ─── MenuSearch: filtering & display ───────────────────────────────────────────

    // Flatten a nested item tree into a searchable list, preserving breadcrumb names.
    function flattenMenu(items, prefix) {
        let flattened = [];
        for (const item of items) {
            const displayName = prefix ? prefix + " / " + item.name : item.name;
            flattened.push(Object.assign({}, item, {
                displayName: displayName
            }));
            if (item.items)
                flattened = flattened.concat(flattenMenu(item.items, displayName));
        }
        return flattened;
    }

    function fuzzyMatch(str, query) {
        str = str.toLowerCase();
        query = query.toLowerCase();
        let qi = 0;
        for (let si = 0; si < str.length && qi < query.length; si++) {
            if (str[si] === query[qi])
                qi++;
        }
        return qi === query.length;
    }

    function getFilteredMenuItems() {
        const query = menuQuery.trim();
        if (query === "")
            return currentMenuItems;

        const matches = searchableMenuItems.filter(item => fuzzyMatch(item.name, query));
        const calculation = menuCalculatorEnabled ? calculate(query) : null;

        if (calculation !== null)
            return matches.concat([
                {
                    name: query + " = " + calculation,
                    icon: "󰃬",
                    result: calculation,
                    calculator: true
                }
            ]);

        if (matches.length === 0 && menuWebSearchEnabled)
            return [
                {
                    name: "Search: " + query,
                    icon: "󰖟",
                    query: query,
                    googleSearch: true
                }
            ];

        return matches;
    }

    // Highlight the individual characters matched by the fuzzy algorithm.
    function highlightedText(text) {
        const value = String(text);
        const query = menuQuery.trim();
        if (query === "" || value.startsWith("Search: "))
            return escapeHtml(value);

        const lowerValue = value.toLowerCase();
        const lowerQuery = query.toLowerCase();

        // Mark which indices in value were consumed by the fuzzy match.
        const matched = new Array(value.length).fill(false);
        let qi = 0;
        for (let si = 0; si < lowerValue.length && qi < lowerQuery.length; si++) {
            if (lowerValue[si] === lowerQuery[qi]) {
                matched[si] = true;
                qi++;
            }
        }
        if (qi < lowerQuery.length)
            return escapeHtml(value);

        // Build output, opening/closing a span around consecutive matched chars.
        let result = "";
        let inSpan = false;
        for (let i = 0; i < value.length; i++) {
            if (matched[i] && !inSpan) {
                result += "<span style=\"color: " + accent + "\">";
                inSpan = true;
            } else if (!matched[i] && inSpan) {
                result += "</span>";
                inSpan = false;
            }
            result += escapeHtml(value[i]);
        }
        if (inSpan)
            result += "</span>";
        return result;
    }

    // Returns true when item matches the currently active power profile.
    function isCurrentPerformanceItem(item) {
        if (!item || !item.command)
            return false;
        if (item.command === "powerprofilesctl set performance")
            return performanceProfile === "performance";
        if (item.command === "powerprofilesctl set balanced")
            return performanceProfile === "balanced";
        if (item.command === "powerprofilesctl set power-saver")
            return performanceProfile === "power-saver";
        return false;
    }

    // ─── MenuSearch: internal helpers ──────────────────────────────────────────────

    function resetMenuView() {
        if (launcher.menuInputItem)
            launcher.menuInputItem.text = "";
        if (launcher.menuListItem)
            launcher.menuListItem.currentIndex = 0;
    }

    function focusMenuInput() {
        if (launcher.menuInputItem)
            launcher.menuInputItem.forceActiveFocus();
    }

    function resetMenu() {
        menuStack = [];
        confirmItem = null;
        confirmSelection = "confirm";
        menuQuery = "";
        openedAsSubmenu = false;
        activeLauncherSubmenu = "";
        resetMenuView();
    }

    // ─── Utilities ───────────────────────────────────────────────────────────

    readonly property string terminal: "kitty"

    function launchDesktop(id) {
        const entry = DesktopEntries.byId(id) || (!String(id).endsWith(".desktop") ? DesktopEntries.byId(id + ".desktop") : null);
        if (entry)
            entry.execute();
    }

    function launchTerminal(klass, title, cmd, pause) {
        const shellCmd = pause ? cmd + "; echo; printf '\\033[38;5;141mPress Enter to close...\\033[0m'; read -r" : cmd;
        const terminalCmd = "exec " + terminal + " --class " + shellQuote(klass) + " --title " + shellQuote(title) + " -e bash -lic " + shellQuote(shellCmd);
        const finalCmd = "uwsm app -- bash -lc " + shellQuote(terminalCmd);

        launchProcess.command = ["hyprctl", "dispatch", "hl.dsp.exec_cmd(" + luaQuote(finalCmd) + ")"];
        launchProcess.running = true;
    }

    // Ask Hyprland to spawn apps so process creation follows the compositor's
    // normal exec path instead of inheriting Quickshell's QProcess scope.
    function runDetached(command) {
        const trimmed = command.trim();

        // Allow menu items to call Hyprland Lua dispatchers directly. This is
        // needed for actions like hl.dsp.exit(), which are not shell commands
        // and must not be wrapped in hl.dsp.exec_cmd(...).
        if (trimmed.startsWith("hl.dsp.")) {
            launchProcess.command = ["hyprctl", "dispatch", trimmed];
            launchProcess.running = true;
            return;
        }

        const shellMeta = /[|&;<>()`$\\\n]/.test(trimmed);
        const finalCmd = trimmed.startsWith("uwsm app") ? trimmed : shellMeta ? "uwsm app -- bash -lc " + shellQuote(trimmed) : "uwsm app -- " + trimmed;

        launchProcess.command = ["hyprctl", "dispatch", "hl.dsp.exec_cmd(" + luaQuote(finalCmd) + ")"];
        launchProcess.running = true;
    }

    function luaQuote(text) {
        return "\"" + String(text).replace(/\\/g, "\\\\").replace(/\"/g, "\\\"").replace(/\n/g, "\\n") + "\"";
    }

    function shellQuote(text) {
        return "'" + String(text).replace(/'/g, "'\\''") + "'";
    }

    function escapeHtml(text) {
        return String(text).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    }

    // Simple recursive-descent calculator for inline expression evaluation.
    function calculate(expression) {
        let text = expression.replace(/\[/g, "(").replace(/\]/g, ")").replace(/×/g, "*").replace(/÷/g, "/");
        text = text.replace(/,/g, ".").replace(/\s+/g, "");
        if (text === "" || !/[0-9]/.test(text) || /[^0-9+\-*/^().]/.test(text))
            return null;

        let index = 0;
        function peek() {
            return text[index];
        }
        function consume(t) {
            if (text[index] === t) {
                index++;
                return true;
            }
            return false;
        }

        function parseNumber() {
            const start = index;
            while (/[0-9.]/.test(peek() || ""))
                index++;
            if (start === index)
                throw "number expected";
            const raw = text.slice(start, index);
            if ((raw.match(/\./g) || []).length > 1)
                throw "invalid number";
            return Number(raw);
        }
        function parsePrimary() {
            if (consume("+"))
                return parsePrimary();
            if (consume("-"))
                return -parsePrimary();
            if (consume("(")) {
                const v = parseAddSub();
                if (!consume(")"))
                    throw "missing )";
                return v;
            }
            return parseNumber();
        }
        function parsePower() {
            let v = parsePrimary();
            if (consume("^"))
                v = Math.pow(v, parsePower());
            return v;
        }
        function parseMulDiv() {
            let v = parsePower();
            while (true) {
                if (consume("*"))
                    v *= parsePower();
                else if (consume("/"))
                    v /= parsePower();
                else
                    return v;
            }
        }
        function parseAddSub() {
            let v = parseMulDiv();
            while (true) {
                if (consume("+"))
                    v += parseMulDiv();
                else if (consume("-"))
                    v -= parseMulDiv();
                else
                    return v;
            }
        }

        try {
            const value = parseAddSub();
            if (index !== text.length || !isFinite(value))
                return null;
            return Number(value.toFixed(10)).toString();
        } catch (e) {
            return null;
        }
    }

    // ─── Processes ───────────────────────────────────────────────────────────

    Process {
        id: launchProcess
    }

    // Parses the pipe-delimited output of bar.sh into individual status fields.
    Process {
        id: statusProcess
        stdout: StdioCollector {
            onStreamFinished: {
                const parts = this.text.trim().split("|");
                if (parts.length >= 5) {
                    root.ramText = parts[0];
                    root.wifiText = parts[1];
                    root.bluetoothText = parts[2];
                    root.batteryText = parts[3];
                    root.volumeText = parts[4];
                    root.screenShareText = parts.length >= 6 ? parts[5] : "";
                }
            }
        }
    }

    Process {
        id: profileProcess
        stdout: StdioCollector {
            onStreamFinished: root.performanceProfile = this.text.trim()
        }
    }

    // ─── Timer ───────────────────────────────────────────────────────────────

    Timer {
        id: osdTimer
        interval: 2000
        onTriggered: root.osdVisible = false
    }

    Timer {
        id: peekTimer
        interval: 3000
        onTriggered: root.barVisible = false
    }

    Timer {
        interval: 1000
        running: true
        repeat: true
        triggeredOnStart: true
        onTriggered: {
            root.timeText = Qt.formatDateTime(new Date(), "ddd dd MMM HH:mm:ss");

            statusProcess.running = false;
            statusProcess.command = ["bash", "-c", root.assetDir + "/scripts/shell/bar.sh"];
            statusProcess.running = true;

            profileProcess.running = false;
            profileProcess.command = ["bash", "-c", "command -v powerprofilesctl >/dev/null 2>&1 && powerprofilesctl get || true"];
            profileProcess.running = true;
        }
    }

    // ─── IPC ─────────────────────────────────────────────────────────────────

    IpcHandler {
        target: "bar"
        function toggle(): void {
            peekTimer.stop();
            root.barVisible = !root.barVisible;
        }
        function show(): void {
            peekTimer.stop();
            root.barVisible = true;
        }
        function hide(): void {
            peekTimer.stop();
            root.barVisible = false;
        }
        function peek(): void {
            root.barVisible = true;
            peekTimer.restart();
        }
    }

    IpcHandler {
        target: "theme"
        function open(): void {
            if (root.themeOpen) {
                root.themeOpen = false;
            }
            root.themeOpen = true;
        }
    }

    IpcHandler {
        target: "processes"
        function open(): void {
            if (root.processOpen) {
                root.processOpen = false;
            }
            root.processScreen = screenForName(Hyprland.focusedMonitor ? Hyprland.focusedMonitor.name : "") || root.processScreen;
            root.processOpen = true;
        }
        function close(): void {
            root.processOpen = false;
        }
    }

    IpcHandler {
        target: "wallpaper"
        function open(): void {
            if (root.wallpaperOpen) {
                root.wallpaperOpen = false;
            }
            root.wallpaperOpen = true;
        }
    }

    IpcHandler {
        target: "osd"
        // Expects a single "icon:value" string, e.g. "󰕾:75"
        function trigger(data: string): void {
            const sep = data.lastIndexOf(":");
            root.osdIcon = data.slice(0, sep);
            root.osdValue = parseInt(data.slice(sep + 1)) || 0;
            root.osdVisible = true;
            osdTimer.restart();
        }
    }

    IpcHandler {
        target: "launcher"
        function open(): void {
            if (root.menuOpen) {
                root.menuOpen = false;
            }

            root.launcherScreen = screenForName(Hyprland.focusedMonitor ? Hyprland.focusedMonitor.name : "") || root.launcherScreen;
            root.menuOpen = true;
        }
        function close(): void {
            root.menuOpen = false;
        }
        function openSubmenu(targetName: string): void {
            if (root.menuOpen && root.activeLauncherSubmenu.toLowerCase() === String(targetName).toLowerCase())
                return;

            if (root.menuOpen) {
                root.menuOpen = false;
            }

            root.launcherScreen = screenForName(Hyprland.focusedMonitor ? Hyprland.focusedMonitor.name : "") || root.launcherScreen;
            if (targetName) {
                let path = [];
                if (findMenuPath(menuItems, targetName, path)) {
                    menuStack = path;
                    openedAsSubmenu = true;
                    activeLauncherSubmenu = targetName;
                }
            }

            root.menuOpen = true;
        }
    }

    // ─── Windows ─────────────────────────────────────────────────────────────

    // One Bar per monitor, each bound to its own screen.
    Variants {
        model: Quickshell.screens
        Bar {
            required property var modelData
            screen: modelData
            shell: root
        }
    }

    Variants {
        model: Quickshell.screens
        Osd {
            required property var modelData
            screen: modelData
            shell: root
        }
    }

    PickerTheme {
        shell: root
    }
    ProcessManager {
        shell: root
    }
    Launcher {
        id: launcher
        shell: root
    }
    PickerWallpaper {
        shell: root
    }
}
