pcall(require, "nix.input")
pcall(require, "nix.voxtype")
require("nix.colors")
require("nix.theme")
require("config.settings")
require("config.animations")
require("config.window_rules")
require("config.monitors")
require("config.keybindings")
require("nix.shell").setup()
