{ config, configDir, ... }:

{
  wayland.windowManager.hyprland = {
    enable = true;
    systemd.enable = false; # UWSM handles the session
  };

  xdg.configFile."hypr/hyprland.lua".text = ''
    local config_dir = "${configDir}/.config/hyprland"

    -- Generated by home-manager so configDir only needs changing in home.nix.
    dofile(config_dir .. "/config/_startup.lua")
    dofile(config_dir .. "/config/monitors.lua")
    dofile(config_dir .. "/config/settings.lua")
    dofile(config_dir .. "/config/animations.lua")
    dofile(config_dir .. "/config/keybindings.lua")
    dofile(config_dir .. "/config/windowrules.lua")
  '';
}
