-- ============================================================
-- Monitors
-- ============================================================

local function assignWorkspaces(monitor, workspaces)
	for _, ws in ipairs(workspaces) do
		hl.workspace_rule({ workspace = tostring(ws), monitor = monitor, default = true })
	end
end

assignWorkspaces("eDP-1", { 1, 2, 3 })
assignWorkspaces("HDMI-A-1", { 4, 5, 6, 7, 8, 9 })

hl.monitor({
	output = "eDP-1",
	mode = "1920x1080@60",
	position = "0x0",
	scale = 1,
})

hl.monitor({
	output = "HDMI-A-1",
	mode = "3440x1440@174.96",
	position = "1920x0",
	scale = 1,
})

-- ============================================================
-- Config
-- ============================================================
hl.config({
	-- input
	input = {
		accel_profile = "flat",
		sensitivity = 1.5,
		repeat_rate = 35,
		repeat_delay = 200,
	},
	cursor = {
		no_hardware_cursors = true,
	},

	-- cosmetics
	general = {
		gaps_in = 4,
		gaps_out = 8,
		border_size = 1,
		layout = "dwindle",
		col = {
			active_border = "rgba(1a1b26ff)",
			inactive_border = "rgba(1a1b26ff)",
		},
	},

	decoration = {
		rounding = 1,
		active_opacity = 0.93,
		inactive_opacity = 0.90,
		fullscreen_opacity = 1.0,
		blur = {
			enabled = true,
			special = true,
			size = 2,
			passes = 3,
			xray = true,
		},
		shadow = {
			enabled = true,
			range = 30,
			render_power = 100,
			color = 0x33000000,
			color_inactive = 0x22000000,
			offset = { 0, 4 },
		},
	},
	animations = { enabled = true },
	layout = {
		single_window_aspect_ratio = { 16, 9 },
	},

	-- misc
	dwindle = { preserve_split = true },
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
		focus_on_activate = true,
	},
})

-- Optional runtime palette generated by active desktop shell.
pcall(require, "dms.colors")

-- trackpad specific settings
local TOUCHPAD = "msft0001:01-06cb:cd5f-touchpad"
hl.device({
	name = TOUCHPAD,
	accel_profile = "adaptive",
	natural_scroll = true,
	sensitivity = 0.0,
})

-- Navigate workspaces vertically
hl.gesture({ fingers = 3, direction = "vertical", action = "workspace" })

-- ============================================================
-- animations
-- ============================================================

hl.curve("spring", {
	type = "spring",
	mass = 1,
	stiffness = 105,
	dampening = 19,
})

hl.curve("fast", {
	type = "bezier",
	points = { { 0.05, 0.7 }, { 0.1, 1.0 } },
})

local animations = {
	{ enabled = true, leaf = "windows", speed = 2, spring = "spring" },
	{ enabled = true, leaf = "windowsOut", speed = 2, spring = "spring" },
	{ enabled = true, leaf = "workspaces", speed = 2, bezier = "fast", style = "slidevert" },
	{ enabled = true, leaf = "specialWorkspace", speed = 2, bezier = "fast", style = "slidevert" },
	{ enabled = true, leaf = "fade", speed = 1, bezier = "fast" },
}

for _, animation in ipairs(animations) do
	hl.animation(animation)
end

-- ============================================================
-- keybinds
-- ============================================================

-- Dank Material Shell
hl.bind("SUPER + Space", hl.dsp.exec_cmd("dms ipc call spotlight toggle"))
hl.bind("SUPER + P", hl.dsp.exec_cmd("dms ipc call processlist toggle"))

-- suspend on power off
hl.bind("XF86PowerOff", hl.dsp.exec_cmd("systemctl suspend"), { locked = true })
-- laptop lid suspends the computer
hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd("systemctl suspend"), { locked = true })

-- apps
hl.bind("SUPER + S", hl.dsp.workspace.toggle_special("terminal"))
hl.bind("SUPER + E", hl.dsp.exec_cmd("uwsm app -- kitty --class yazi --title yazi -e yazi"))
hl.bind("SUPER + Return", hl.dsp.exec_cmd("uwsm app -- kitty"))

-- workspaces
hl.bind("SUPER + W", hl.dsp.window.close())
hl.bind("SUPER + J", hl.dsp.layout("togglesplit"))
hl.bind("SUPER + T", hl.dsp.window.float({ action = "toggle" }))

hl.bind(
	"SUPER + F",
	hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }),
	{ desc = "Toggle fullscreen" }
)

hl.bind("SUPER + Tab", hl.dsp.focus({ workspace = "previous" }))

for _, dir in ipairs({ "left", "right", "up", "down" }) do
	hl.bind("SUPER + " .. dir, hl.dsp.focus({ direction = dir }))
	hl.bind("SUPER + SHIFT + " .. dir, hl.dsp.window.move({ direction = dir }))
end

for ws = 1, 9 do
	hl.bind("SUPER + " .. ws, hl.dsp.focus({ workspace = ws }))
	hl.bind("SUPER + SHIFT + " .. ws, hl.dsp.window.move({ workspace = ws }))
end

-- window resizing
-- Expand horizontally (increase width)
hl.bind("SUPER + equal", hl.dsp.window.resize({ x = 100, y = 0, relative = true }))

-- Shrink horizontally (decrease width)
hl.bind("SUPER + minus", hl.dsp.window.resize({ x = -100, y = 0, relative = true }))

hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- hypr shortcuts
hl.bind("SUPER + SHIFT + K", hl.dsp.exec_cmd("hyprpicker"))

-- screenshot
local screenshot_cmd = "mkdir -p ~/Screenshots && "
	.. 'file="$HOME/Screenshots/screenshot-$(date +%Y%m%d-%H%M%S).png" && '
	.. 'grim -g "$(slurp)" "$file" && wl-copy --type image/png < "$file"'
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd(screenshot_cmd))

-- nixos helpers
local function openTerminal(klass, cmd, pause)
	local tail = pause == false and "" or '; echo; printf "\\033[38;5;141mPress Enter to close...\\033[0m"; read -r'
	return hl.dsp.exec_cmd(
		"uwsm app -- kitty --class " .. klass .. " --title " .. klass .. " -e bash -lic '" .. cmd .. tail .. "'"
	)
end

-- universal copy / paste
local universal_shortcut_pressed = {}

local function sendShortcutOnce(mods, key)
	-- Clear any stale synthetic state, then send a short, real-looking tap.
	hl.dispatch(hl.dsp.send_key_state({ mods = mods, key = key, state = "up" }))
	hl.dispatch(hl.dsp.send_key_state({ mods = mods, key = key, state = "down" }))
	hl.timer(function()
		hl.dispatch(hl.dsp.send_key_state({ mods = mods, key = key, state = "up" }))
	end, { timeout = 90, type = "oneshot" })
end

local function bindShortcut(bind, mods, key, desc, windowsMods, windowsKey)
	hl.bind(bind, function()
		if universal_shortcut_pressed[bind] then
			return
		end
		universal_shortcut_pressed[bind] = true

		local shortcutMods = mods
		local shortcutKey = key
		local win = hl.get_active_window()
		if win and win.class == "windows-vm" then
			shortcutMods = windowsMods or mods
			shortcutKey = windowsKey or key
		end
		sendShortcutOnce(shortcutMods, shortcutKey)

		-- Safety reset in case Hyprland misses the release event during focus churn.
		hl.timer(function()
			universal_shortcut_pressed[bind] = false
			hl.dispatch(hl.dsp.send_key_state({ mods = shortcutMods, key = shortcutKey, state = "up" }))
		end, { timeout = 1200, type = "oneshot" })
	end, { desc = desc })

	hl.bind(bind, function()
		universal_shortcut_pressed[bind] = false
	end, { release = true })
end

bindShortcut("SUPER + X", "SHIFT", "Delete", "Universal cut")
bindShortcut("SUPER + C", "CTRL", "Insert", "Universal copy", "CTRL", "C")
bindShortcut("SUPER + V", "SHIFT", "Insert", "Universal paste", "CTRL", "V")

-- toggle single window aspect ratio
local single_window_aspect_enabled = true
hl.bind("SUPER + M", function()
	single_window_aspect_enabled = not single_window_aspect_enabled
	if single_window_aspect_enabled then
		hl.config({ layout = { single_window_aspect_ratio = { 16, 9 } } })
	else
		hl.config({ layout = { single_window_aspect_ratio = { 0, 0 } } })
	end
end, { desc = "Toggle single-window max width" })

-- media / brightness
local media = {
	{ "XF86AudioRaiseVolume", "dms ipc call audio increment 5" },
	{ "XF86AudioLowerVolume", "dms ipc call audio decrement 5" },
	{ "XF86AudioMute", "dms ipc call audio mute" },
	{ "XF86AudioMicMute", "dms ipc call audio micmute" },
	{ "XF86MonBrightnessUp", 'dms ipc call brightness increment 5 ""' },
	{ "XF86MonBrightnessDown", 'dms ipc call brightness decrement 5 ""' },
}
for _, b in ipairs(media) do
	hl.bind(b[1], hl.dsp.exec_cmd(b[2]), { locked = true, repeating = true })
end

-- ============================================================
-- Window  & Layer Rules
-- ============================================================

local popup_windows = {
	{ title = "wifi-manager" },
	{ title = "bluetooth-manager" },
	{ title = "performance-monitor" },
	{ title = "audio-manager" },

	{ title = "windows-install" },
	{ title = "windows-uninstall" },
	{ title = "windows-credentials" },
	{ title = "windows-vm-start" },

	{ title = "nixos-refresh" },
	{ title = "nixos-build" },
	{ title = "nixos-update" },
	{ title = "nixos-check" },
	{ title = "nixos-install" },
	{ title = "nixos-remove" },

	{ title = "webapp-install" },
	{ title = "webapp-uninstall" },

	{ class = "xdg-desktop-portal-gtk" },
	{ class = "termfilechooser" },
	{ class = "1password" },
	{ class = "lazy-docker" },

	{ class = "yazi" },
}

for _, w in ipairs(popup_windows) do
	hl.window_rule({
		match = w.title and { title = w.title } or { class = w.class },
		float = true,
		center = true,
		size = w.size or { 1300, 800 },
		pin = w.pin,
		stay_focused = w.stay_focused,
	})
end

hl.window_rule({
	match = { title = ".*(Screen is being shared|Screen Share Active).*" },
	workspace = "special:screenshare-preview silent",
	no_focus = true,
	suppress_event = "activate activatefocus",
})

hl.layer_rule({
	match = { namespace = "^ch\\.wysbd\\.hyprland-preview-share-picker$" },
	blur = true,
	xray = true,
	ignore_alpha = 0.01,
})

hl.window_rule({ match = { float = true }, opacity = "0.935 override 0.935 override 1.0 override" })

require("dms.binds")
require("dms.binds-user")
require("dms.outputs")
require("dms.windowrules")
require("dms.layout")
require("dms.cursor")
