{ ... }:

# This file is usually generated by running:
#   nixos-generate-config --root /mnt
# during installation. Copy the generated hardware-configuration.nix here
# and replace the module name with your host name (e.g. exampleHardware).
#
# You can also regenerate it on an existing install:
#   nixos-generate-config --show-hardware-config

{
  flake.systemModules.exampleHardware =
    {
      config,
      lib,
      modulesPath,
      ...
    }:
    {
      # Detects and silences warnings for hardware not found at boot.
      imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

      # Kernel modules loaded into the initrd (early boot, before / is mounted).
      # Common values: "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod"
      # Add "amdgpu" here if you have an AMD GPU and want it available at boot.
      boot.initrd.availableKernelModules = [ ];
      boot.initrd.kernelModules = [ ];

      # Kernel modules loaded after boot.
      # "kvm-intel" or "kvm-amd" depending on your CPU — needed for virtualisation.
      boot.kernelModules = [ ];
      boot.extraModulePackages = [ ];

      # ============================================================
      # Filesystems
      # ============================================================

      # Get UUIDs with: lsblk -o NAME,UUID
      # fsType is usually "ext4" or "btrfs".

      fileSystems."/" = {
        device = "/dev/disk/by-uuid/"; # root partition UUID
        fsType = "ext4";
      };

      # EFI boot partition — only needed if using systemd-boot or GRUB with EFI.
      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/"; # EFI partition UUID
        fsType = "vfat";
        options = [
          "fmask=0077"
          "dmask=0077"
        ];
      };

      # Remove if you have no swap partition.
      swapDevices = [
        { device = "/dev/disk/by-uuid/"; } # swap partition UUID
      ];

      # ============================================================
      # CPU & Platform
      # ============================================================

      # "x86_64-linux" for most desktops/laptops.
      # "aarch64-linux" for ARM (e.g. Raspberry Pi, Apple Silicon via Lima).
      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

      # Pick one depending on your CPU manufacturer:
      hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
      # hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
