services:
  windows:
    image: dockurr/windows:latest
    container_name: Windows
    restart: "no"
    stop_grace_period: 120s

    devices:
      - /dev/kvm
      - /dev/net/tun

    cap_add:
      - NET_ADMIN

    ports:
      - "127.0.0.1:8006:8006"
      - "127.0.0.1:3389:3389/tcp"
      - "127.0.0.1:3389:3389/udp"
      - "127.0.0.1:11433:11433/tcp"

    volumes:
      - ${HOME}/VMs/windows/storage:/storage
      - ${HOME}/VMs/windows/shared:/shared

    environment:
      TZ: "@timeZone@"
      VERSION: "11"
      RAM_SIZE: "@memory@"
      CPU_CORES: "@cpuCores@"
      DISK_SIZE: "@diskSize@"
      USERNAME: ${WINDOWS_USERNAME:-Docker}
      PASSWORD: ${WINDOWS_PASSWORD:?Run windows-install to create ~/.config/nos/secrets/windows.env}
