-- Load feature modules in dependency order.
require("config.options")
require("config.theme")
require("config.colors")
require("config.keymaps")
require("config.ui")
require("config.statusline")
require("config.navigation")
require("config.git")
require("config.search")
require("config.treesitter")
require("config.completion")
require("config.lsp")
require("config.formatting")
require("config.diagnostics")
require("config.debugging")
require("config.testing")
require("config.sessions")
